config/routes.rb
  Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :services
  resources :enquiries
  resources :posts
  resources :appointments

  devise_for :users, controllers: {registrations:'registrations'}

get 'home', to: "pages#home"
get 'about', to: "pages#about"
#get 'contact', to: "pages#contact"
get 'news', to: "pages#news"
get 'services', to: "pages#services"

root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :appointments, dependent: :restrict_with_error
  has_many :users, dependent: :restrict_with_error
  has_many :enquiries, dependent: :restrict_with_error
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="field">
                      <p class="control">
                        <%= f.input :name, label: "Name", input_html: {class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter your name..." , autofocus: true, required: true %>
                      </p>
    </div>
    <div class="field">
                      <p class="control">
                        <%= f.input :description, label: "Description", input_html: {class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter a short description..." , autofocus: true, required: true %>
                      </p>
    </div>
  </div>

  <br>
  <div class="form-actions">
  <p class="control">
      <%= f.button :submit, class: "button is-info" %>
  </p><br>
  <%= link_to 'Back', services_path, class: "button is-primary" %>
</div>
<% end %>

app/views/services/edit.html.erb
<div class="section homeBackground">
  <div class="Container columns is-centered">
    <div class="column is-6">
      <div class="notification">
        <h1 class="title">Edit Service</h1>
        <%= render 'form', service: @service %><br>
      </div>
    </div>
  </div>
</div>

app/views/services/index.html.erb
    <div class="section homeBackground">

      <div class="container">
        <p id="notice"><%= notice %></p>
        <div class="blueish notification">
          <h1 class="title">Services</h1>
        </div>
        <%= link_to 'New Service', new_service_path, class: "button is-info" %>
      </div>
      <% @services.each do |service| %>
      <div class="container section">
        <div class=" is-centered ">
          <div class="">
            <article class="message is-multiline">
                <div class="message-header">
                    <p>
                      <%= service.name %>
                    </p>
                    <nav class="level">
                      <div class="level-left">
                        <div class="tag is-primary level-item">
                      <span class="icon">

                              <i class="fa fa-id-badge" aria-hidden="true"></i>
                            </span>
                      id:[<%= service.id %>]
                    </div>
                    <div class="tag is-primary level-item">
                      <span class="icon">

                              <i class="fa fa-clock-o" aria-hidden="true"></i>
                            </span>
                      <%= service.created_at%><br>
                    </div>
                      </div>
                    </nav>


                </div>
                <div class="message-body">
                  <p class="content">
                    <div class="notification is-primary">
                      <%= service.description%><br>
                    </div>

                    <span class="tag is-primary"><%= link_to "Show", service_path(service) %></span><br>
                    <span class="tag is-primary"><%= link_to 'Edit', edit_service_path(service) %></span><br>
                </p>
                </div>
                <nav class="level">
                  <div class="level-left">

                  </div>
                  <!-- Right side-->
                  <div class="level-right">
                    <p class="level-item">
                      <span class="icon">

                      </span>
                      <%=link_to "Delete", service_path(service), method: :delete, data: {confirm:"Are you sure? "}, class: "button is-danger" %>
                    </p>
                  </div>
                </nav>
            </article>

          </div>
      </div>
      </div>
<% end %>
    </div>

app/views/services/new.html.erb
<div class="section homeBackground">
  <div class="container columns is-centered">
    <div class="column is-6">
      <h1 class="title notification is-primary">New Service</h1>
      <div class="box">
        <%= render 'form', service: @service %>
      </div>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="homeBackground section">
  <p id="notice"><%= notice %></p>
    <div class="notification blueish">
      <h1 class="title">Services</h1>
    </div>


    <div class="container section">
        <article class="message is-multiline">
            <div class="message-header">
                <p>
                  <%= @service.name %>
                </p>
                <nav class="level">
                  <div class="level-left">
                    <div class="tag is-primary level-item">
                  <span class="icon">

                          <i class="fa fa-id-badge" aria-hidden="true"></i>
                  </span>
                  id:[<%= @service.id %>]
                </div>
                <div class="tag is-primary level-item">
                  <span class="icon">

                          <i class="fa fa-clock-o" aria-hidden="true"></i>
                        </span>
                  <%= @service.created_at%><br>
                </div>
                  </div>
                </nav>


            </div>
            <div class="message-body">
              <p class="content">
                <div class="notification is-primary">
                  <%= @service.description%><br>
                </div>
                <nav class="level">
                  <div class="level-left">

                  </div>
                  <!-- Right side-->
                  <div class="level-right">
                    <p class="level-item">
                      <%= link_to 'Edit', edit_service_path(@service), class: "button is-primary" %> |
                      <%= link_to 'Back', services_path, class: "button is-primary" %>
                    </p>
                  </div>
                </nav>
            </p>
            </div>
        </article>

  </div>

</div>