config/routes.rb
  Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :services
  resources :enquiries
  resources :posts
  resources :appointments

  devise_for :users, controllers: {registrations:'registrations'}

get 'home', to: "pages#home"
get 'about', to: "pages#about"
#get 'contact', to: "pages#contact"
get 'news', to: "pages#news"
get 'services', to: "pages#services"

root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))


    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :title, label: "Title", input_html: { class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter a title...", autofocus: true %>
  </div>
</div>
<div class="field">
  <div class="control">
    <%= f.input :description, label: "Description", input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "write your post...", autofocus: true %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/posts/edit.html.erb
<div class="section homeBackground">
  <div class="Container columns is-centered">
    <div class="column is-6">
      <div class="notification">
        <h1 class="title">New Post</h1>
        <%= render 'form', post: @post %><br>
        <%= link_to 'Back', posts_path, class: "button is-info" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="section homeBackground">
  <div class="notification container blueish">
    <h1 class="title">Posts</h1>
  </div>

  <% @posts.each do |post| %>
  <div class="">
    <div class="container">
      <div class="columns is-centered">
      <div class="column is-7">
        <div class="notification">
          <article class="message is-multiline">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <%= image_tag "inject.jpg" %>
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4"><%= post.title %></p>
                <p class="subtitle is-6">created by:
                  <strong><%= post.user.name %></strong>
                </p>
              </div>
            </div>
              <div class="message-header">
                  <nav class="level">
                    <div class="level-left">
                      <div class="tag is-primary level-item">
                    <span class="icon">

                            <i class="fa fa-id-badge" aria-hidden="true"></i>
                          </span>
                    id:[<%= post.id %>]
                  </div>
                  <div class="tag is-primary level-item">
                    <span class="icon">

                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                          </span>
                    <%= post.created_at%><br>
                  </div>
                    </div>
                  </nav>


              </div>
              <div class="message-body">
                <p class="content">
                  <div class="has-text-weight-semibold">Post:</div>
                  <div class="notification box">
                    <%= post.description%><br>
                  </div>
                  <span class="tag is-primary"><%= link_to "Show", post_path(post) %></span>

                  <a class="tag is-primary" href="#">
                    Comment
                  <span class="icon">

                          <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                  </a>
              </p>
              </div>
              <nav class="level">
                <div class="level-left">

                </div>
                <!-- Right side-->
                <% if user_signed_in? %>
                <% if current_user.name == post.user.name %>

                <div class="level-right">
                  <p class="level-item">
                    <%= link_to 'Edit', edit_post_path(post), class: "button is-primary" %>
                  </p>
                  <p class="level-item">
                    <%=link_to "Delete", post_path(post), method: :delete, data: {confirm:"Are you sure? "}, class: "button is-danger" %>
                  </p>
                </div>
                <% end %>
                <% end %>


              </nav>
          </article>
        </div>
      </div>
    </div>
    </div><br>

  </div>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="section homeBackground">
  <div class="Container columns is-centered">
    <div class="column is-6">
      <div class="notification">
        <h1 class="title">New Post</h1>
        <%= render 'form', post: @post %><br>
        <%= link_to 'Back', posts_path, class: "button is-info" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="section homeBackground">
  <p id="notice"><%= notice %></p>
  <div class="notification container blueish">
    <h1 class="title">posts</h1>
  </div>

  <div class=" ">
    <div class="container">
      <div class="columns is-centered">
      <div class="column is-7">
        <div class="notification">
          <article class="message is-multiline">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <%= image_tag "inject.jpg" %>
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4"><%= @post.title %></p>
                <p class="subtitle is-6">created by:
                  <strong><%= @post.user.name %></strong>
                </p>
              </div>
            </div>
              <div class="message-header">
                  <nav class="level">
                    <div class="level-left">
                      <div class="tag is-primary level-item">
                    <span class="icon">

                            <i class="fa fa-id-badge" aria-hidden="true"></i>
                          </span>
                    id:[<%= @post.id %>]
                  </div>
                  <div class="tag is-primary level-item">
                    <span class="icon">

                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                          </span>
                    <%= @post.created_at%><br>
                  </div>
                    </div>
                  </nav>


              </div>
              <div class="message-body">
                <p class="content">
                  <div class="has-text-weight-semibold">Post:</div>
                  <div class="notification box">
                    <%= @post.description%><br>
                  </div>
                  <a class="tag is-primary" href="#">
                    Comment
                  <span class="icon">

                          <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                  </a><br>
                  <span class="tag is-primary"><%= link_to 'Back', posts_path %></span>
              </p>
              </div>
              <% if user_signed_in? %>
              <nav class="level">
                <div class="level-left">

                </div>
                <!-- Right side-->
                <div class="level-right">
                  <p class="level-item">
                    <%= link_to 'Edit', edit_post_path(@post), class: "button is-primary" %>
                  </p>
                  <p class="level-item">
                    <%=link_to "Delete", post_path(@post), method: :delete, data: {confirm:"Are you sure? "}, class: "button is-danger" %>
                  </p>
                </div>
              </nav>
              <% end %>


              </p>
              </div>

          </article>
        </div>
      </div>
    </div>
    </div>

</div>