config/routes.rb
  Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :services
  resources :enquiries
  resources :posts
  resources :appointments

  devise_for :users, controllers: {registrations:'registrations'}

get 'home', to: "pages#home"
get 'about', to: "pages#about"
#get 'contact', to: "pages#contact"
get 'news', to: "pages#news"
get 'services', to: "pages#services"

root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/enquiry.rb
class Enquiry < ApplicationRecord
  belongs_to :service
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  before_action :set_enquiry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new, :create]

  # GET /enquiries
  # GET /enquiries.json
  def index
    @enquiries = Enquiry.all
  end

  # GET /enquiries/1
  # GET /enquiries/1.json
  def show
  end

  # GET /enquiries/new
  def new
    @enquiry = Enquiry.new
  end

  # GET /enquiries/1/edit

  # POST /enquiries
  # POST /enquiries.json
  def create
    @enquiry = Enquiry.new(enquiry_params)
    respond_to do |format|
      if @enquiry.save
        format.html { redirect_to new_enquiry_path, notice: 'Enquiry was successfully created.' }
        format.json { render :show, status: :created, location: @enquiry }

        ClientMailer.new_enquiry(@enquiry).deliver_now
      else
        format.html { render :new }
        format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  def destroy
    @enquiry.destroy
    respond_to do |format|
      format.html { redirect_to enquiries_url, notice: 'Enquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enquiry
      @enquiry = Enquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enquiry_params
      params.require(:enquiry).permit(:name, :contact, :email, :question, :service_id)
    end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= simple_form_for(@enquiry) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="field">
                      <p class="control">
                        <%= f.input :name, label: "Name", input_html: {class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter your name..." , autofocus: true, required: true %>
                      </p>
    </div>
    <div class="field">
                      <p class="control">
                        <%= f.input :contact, label: "Contact", input_html: {class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter your phone number..." , autofocus: true, required: true %>
                      </p>
    </div>
    <div class="field">
                      <p class="control">
                        <%= f.input :email, label: "Email", input_html: {class: "input"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter your email..." , autofocus: true, required: true %>
                      </p>
    </div>
    <div class="field">
      <div class="control">
        <%= f.association :service, wrapper: false , input_html: {class: "input"}, label_html: {class: "label"}%>
      </div>
    </div>
    <div class="field">
							  	<p class="control">
							    	<%= f.input :question, label: "Question", input_html: {class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "Enter your question..." , autofocus: true, required: true %>
		  						</p>
							</div>
  </div>

  <br>
  <div class="form-actions">
  <p class="control">
      <%= f.button :submit, class: "button is-info" %>
  </p><br>
</div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing Enquiry</h1>

<%= render 'form', enquiry: @enquiry %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<div class="section homeBackground">
	<p id="notice"><%= notice %></p>
	<div class="notification blueish">
		<h1 class="title container is-centred">Enquiries</h1>
	</div>
	<% if user_signed_in? %>

	<% @enquiries.each do |enquiry| %>
	<% if current_user.service.name == enquiry.service.name %>
		<div class="container section">
					<article class="message is-multiline">
							<div class="message-header">
									<p>
										<%= enquiry.name %>
									</p>
									<nav class="level">
										<div class="level-left">
											<div class="tag is-primary level-item">
														<span class="icon">

																		<i class="fa fa-id-badge" aria-hidden="true"></i>
														 </span>
														id:[<%= enquiry.id %>]
											</div>
											<div class="tag is-primary level-item">
												<span class="icon">

																<i class="fa fa-clock-o" aria-hidden="true"></i>
												</span>
												<%= enquiry.created_at%><br>
											</div>
										</div>
									</nav>
							</div>
							<div class="message-body">
							<p class="content">
								<strong>
									Email Address:
								<%= enquiry.email%><br>
								</strong>
								<strong>
									Service:
									<%= enquiry.service.name%><br>
								</strong>
								<div class="has-text-weight-semibold">Enquiry:</div>
								<div class="notification is-primary">
									<%= enquiry.question%><br>
								</div>

								<span class="tag is-primary"><%= link_to "Show", enquiry_path(enquiry) %></span><br>

								<a class="tag is-primary" href="#">
									Reply
								<span class="icon">

												<i class="fa fa-envelope" aria-hidden="true"></i>
											</span>
								</a>
							</p>
							</div>
							<nav class="level">
								<div class="level-left">

								</div>
								<!-- Right side-->
								<div class="level-right">
									<p class="level-item">
										<span class="icon">

										</span>
										<%=link_to "Delete", enquiry_path(enquiry), method: :delete, data: {confirm:"Are you sure? "}, class: "button is-danger" %>
									</p>
								</div>
							</nav>
					</article>
		</div>
			<% end %>
	<% end %>
	<% end %>

		</div>

app/views/enquiries/new.html.erb
<div class="section homeBackground">
  <div class="container">
    <div class="notification blueish">
				<div class="has-text-centered">
				 <h2 class="title">Talk to us</h2>
			    </div>
		</div>
    <div class="columns">
      <div class="column is-6">
        <div class="notification">
			  		<h2 class="subtitle">
			  			Make enquiries
			  		</h2>
			  </div>
        <div class="notification">
            <%= render 'form', enquiry: @enquiry %>
        </div>
      </div>
      <div class="column  is-4">
			    <div class="notification">
			  		<h2 class="subtitle">
			  			Contacts
			  		</h2>
			  	</div>
			  	<div class="notification has-text-centered">
			  		<p class="card-content">
			  			<span class="icon">
		                  		<i class="fa fa-phone" aria-hidden="true"></i>
		                </span><span>Talk to us :</span><br>

			  			0721456789<br>
			  			----------or----------<br>
			  			<span class="icon">
		                  		<i class="fa fa-envelope" aria-hidden="true"></i>
		                </span><span>E-mail us at :</span><br>

			  			ROSC@gmail.com
			  		</p>
			  	</div>
			  </div>
			  <div class="column  is-2">
				    <div class="notification">
				  		<h2 class="subtitle">
				  			Connect
				  		</h2>
				  	</div>
				  	<div class="notification has-text-centered">
				  		<p> Find us on :</p>
				  		<p class="content">
				  			<span class="icon">
		                  		<i class="fa fa-twitter" aria-hidden="true"></i>
		                	</span><a href="#">Twitter</a><br>
		                	<span class="icon">
		                  		<i class="fa fa-facebook" aria-hidden="true"></i>
		                	</span><a href="#">facebook</a><br>
		                	<span class="icon">
		                  		<i class="fa fa-instagram" aria-hidden="true"></i>
		                	</span><a href="#">Instagram</a> <br>
				  		</p>
				  	</div>
			  </div>
    </div>
  </div>
</div>

app/views/enquiries/show.html.erb
<div class="section homeBackground">
	<p id="notice"><%= notice %></p>
	<div class="container">
		<div class="columns">
		<div class="column is-9 ">
			<% if user_signed_in? %>
		<% if current_user.service.name == @enquiry.service.name %>
			<div class="card">
				<article class="message is-multiline">
					  <div class="message-header">
						    <p>
						    	<%= @enquiry.name %>
						    </p>
						    <nav class="level">
						    	<div class="level-left">
						    		<div class="tag is-primary level-item">
						    	<span class="icon">

				                  <i class="fa fa-id-badge" aria-hidden="true"></i>
				                </span>
						    	id:[<%= @enquiry.id %>]
						    </div>
						    <div class="tag is-primary level-item">
						    	<span class="icon">

				                  <i class="fa fa-clock-o" aria-hidden="true"></i>
				                </span>
						    	<%= @enquiry.created_at%><br>
						    </div>
						    	</div>
						    </nav>


					  </div>
					  <div class="message-body">
					    <p class="content">
					    	<strong>
					    		Email Address:
								<%= @enquiry.email%><br>
					    	</strong>
								<strong>
									Service:
									<%= @enquiry.service.name%><br>
								</strong>
					    	<div class="has-text-weight-semibold">Enquiry:</div>
					    	<div class="notification is-primary">
					    		<%= @enquiry.question%><br>
					    	</div>
						    <a class="tag is-primary" href="#">
						    	Reply
						    <span class="icon">

			                  <i class="fa fa-envelope" aria-hidden="true"></i>
			                </span>
						    </a>
								<span class="tag is-primary"><%= link_to 'Back', enquiries_path %></span>
						</p>
					  </div>
					  <nav class="level">
							<div class="level-left">

							</div>
							<!-- Right side-->
							<div class="level-right">
								<p class="level-item">
									<%=link_to "Delete", enquiry_path(@enquiry), method: :delete, data: {confirm:"Are you sure? "}, class: "button is-danger" %>
								</p>
							</div>
						</nav>
				</article>
			</div>
			<% end %>
			<% end %>
		</div>
	</div>
	</div>

</div>